CREATE TABLE EMPLOYEE(
	eid INT NOT NULL,
    bdate DATE,
    name VARCHAR(30),
    gender BOOL,
    email VARCHAR(30),
    salary FLOAT,
    address VARCHAR(30),
    PRIMARY KEY (eid)
);

CREATE TABLE NURSE(
	eid INT NOT NULL,
    PRIMARY KEY (eid)
);

CREATE TABLE BUILDING(
	name VARCHAR(10) NOT NULL,
    location VARCHAR(30),
    PRIMARY KEY(name)
);

CREATE TABLE ROOM(
	nid INT,
	room_id INT NOT NULL,
    bname VARCHAR(10) NOT NULL,
    room_type VARCHAR(10),
    capacity INT,
    PRIMARY KEY (room_id, bname)
);

CREATE TABLE DOCTOR(
	eid INT NOT NULL,
    supervisor_id INT,
    fname VARCHAR(30),
    PRIMARY KEY (eid)
);

CREATE TABLE FACULTY(
	name VARCHAR(30) NOT NULL,
    manager_id INT,
    start_date DATE,
    end_date DATE,
    location_address VARCHAR(30),
    PRIMARY KEY(name)
);

CREATE TABLE TREATMENT (
	tid INT NOT NULL,
    pid INT NOT NULL,
    did INT NOT NULL,
    description VARCHAR(1000),
    fee FLOAT,
    result VARCHAR(1000),
    disease VARCHAR(1000),
    discharged_date DATE,
    admitted_date DATE,
    PRIMARY KEY (tid, pid, did)
);

CREATE TABLE TREATMENT_INCLUDE (
	tid INT NOT NULL,
    mcode INT NOT NULL,
    instruction VARCHAR(1000),
    quantity INT,
    PRIMARY KEY (tid, mcode)
);

CREATE TABLE INPATIENT(
	pid INT NOT NULL,
    room_id INT,
    PRIMARY KEY (pid)
);

CREATE TABLE PATIENT(
	pid INT NOT NULL,
    name VARCHAR(100),
    gender BOOL,
    bdate DATE,
    address VARCHAR(100),
    phone_number VARCHAR(100),
    anamnesis VARCHAR(1000),
    PRIMARY KEY (pid)
);

CREATE TABLE MEDICINE(
	code INT NOT NULL,
    name VARCHAR(100),
    price FLOAT,
    PRIMARY KEY (code)
);

CREATE TABLE EXAMINATION(
	exam_id INT NOT NULL,
    pid INT NOT NULL,
    did INT NOT NULL,
    diagnosis VARCHAR(1000),
    date DATE,
    fee FLOAT,
    symptoms VARCHAR(1000),
    PRIMARY KEY (exam_id, pid, did)
);

CREATE TABLE EXAMINATION_INCLUDE(
	ex_id INT NOT NULL,
    mcode INT NOT NULL,
    instruction VARCHAR(1000),
    quantity VARCHAR(1000),
    PRIMARY KEY (ex_id, mcode)
);

CREATE TABLE OUTPATIENT(
	pid INT NOT NULL,
    PRIMARY KEY (pid)
);

CREATE TABLE APPOINTMENT(
	pid INT NOT NULL,
    did INT NOT NULL,
    date DATE NOT NULL,
    PRIMARY KEY (pid, did, date)
);

CREATE TABLE E_PHONE_NUMBERS (
	eid INT NOT NULL,
    phone_no INT NOT NULL,
    PRIMARY KEY(eid, phone_no)
);

CREATE TABLE CARE(
	nid INT NOT NULL,
    pid INT NOT NULL,
    PRIMARY KEY(nid, pid)
);

ALTER TABLE ROOM
ADD  FOREIGN KEY (nid) REFERENCES NURSE(eid) ON DELETE SET NULL ON UPDATE CASCADE,
ADD  FOREIGN KEY (bname) REFERENCES BUILDING(name) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DOCTOR
ADD FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (fname) REFERENCES FACULTY(name) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (supervisor_id) REFERENCES DOCTOR(eid) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE NURSE
ADD FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE FACULTY
ADD  FOREIGN KEY (manager_id) REFERENCES DOCTOR(eid) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TREATMENT
ADD FOREIGN KEY (pid) REFERENCES INPATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (did) REFERENCES DOCTOR(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TREATMENT_INCLUDE
ADD FOREIGN KEY (tid) REFERENCES TREATMENT(tid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (mcode) REFERENCES MEDICINE(code) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INPATIENT
ADD FOREIGN KEY (room_id) REFERENCES ROOM(room_id) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (pid) REFERENCES PATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EXAMINATION
ADD FOREIGN KEY (pid) REFERENCES OUTPATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (did) REFERENCES DOCTOR(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EXAMINATION_INCLUDE
ADD FOREIGN KEY (mcode) REFERENCES MEDICINE(code) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (ex_id) REFERENCES EXAMINATION(exam_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE OUTPATIENT
ADD FOREIGN KEY (pid) REFERENCES PATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE APPOINTMENT
ADD FOREIGN KEY (pid) REFERENCES PATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (did) REFERENCES DOCTOR(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE E_PHONE_NUMBERS
ADD FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CARE
ADD FOREIGN KEY (nid) REFERENCES NURSE(eid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (pid) REFERENCES INPATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE;