/*
****** Initiate tables with no reference.
*/
CREATE TABLE EMPLOYEE(
	eid INT NOT NULL,
    bdate DATE,
    name VARCHAR(30),
    gender BOOL,
    email VARCHAR(30),
    salary FLOAT,
    address VARCHAR(30),
    PRIMARY KEY (eid)
);

CREATE TABLE NURSE(
	eid INT NOT NULL,
    PRIMARY KEY (eid)
);

CREATE TABLE BUILDING(
	name VARCHAR(10) NOT NULL,
    location VARCHAR(30),
    PRIMARY KEY(name)
);

CREATE TABLE ROOM(
	nid INT,
	room_id INT NOT NULL,
    bname VARCHAR(10) NOT NULL,
    room_type VARCHAR(10),
    PRIMARY KEY (room_id, bname)
);

CREATE TABLE ROOMTYPE(
	room_type VARCHAR(10) NOT NULL,
    capacity INT,
    PRIMARY KEY (room_type)
);

CREATE TABLE DOCTOR(
	eid INT NOT NULL,
    supervisor_id INT,
    fname VARCHAR(30),
    PRIMARY KEY (eid)
);

CREATE TABLE FACULTY(
	name VARCHAR(30) NOT NULL,
    manager_id INT,
    start_date DATE,
    end_date DATE,
    location_address VARCHAR(30),
    PRIMARY KEY(name)
);

CREATE TABLE TREATMENT (
	tid INT NOT NULL,
    pid INT NOT NULL,
    did INT NOT NULL,
    description VARCHAR(1000),
    fee FLOAT,
    result VARCHAR(1000),
    disease VARCHAR(1000),
    discharged_date DATE,
    admitted_date DATE,
    PRIMARY KEY (tid, pid, did)
);

CREATE TABLE TREATMENT_INCLUDE (
	tid INT NOT NULL,
    pid INT NOT NULL,
    did INT NOT NULL,
    mcode INT NOT NULL,
    instruction VARCHAR(1000),
    quantity INT,
    PRIMARY KEY (tid, pid, did, mcode)
);

CREATE TABLE INPATIENT(
	pid INT NOT NULL,
    room_id INT,
    PRIMARY KEY (pid)
);

CREATE TABLE PATIENT(
	pid INT NOT NULL,
    name VARCHAR(30),
    gender BOOL,
    bdate DATE,
    address VARCHAR(100),
    phone_number VARCHAR(100),
    anamnesis VARCHAR(1000),
    PRIMARY KEY (pid)
);

CREATE TABLE MEDICINE(
	code INT NOT NULL,
    name VARCHAR(100),
    price FLOAT,
    PRIMARY KEY (code)
);

CREATE TABLE EXAMINATION(
	exam_id INT NOT NULL,
    pid INT NOT NULL,
    did INT NOT NULL,
    diagnosis VARCHAR(1000),
    date DATE,
    fee FLOAT,
    symptoms VARCHAR(1000),
    PRIMARY KEY (exam_id, pid, did)
);

CREATE TABLE EXAMINATION_INCLUDE(
	ex_id INT NOT NULL,
    pid INT NOT NULL,
    did INT NOT NULL,
    mcode INT NOT NULL,
    instruction VARCHAR(1000),
    quantity VARCHAR(1000),
    PRIMARY KEY (ex_id, pid, did, mcode)
);

CREATE TABLE OUTPATIENT(
	pid INT NOT NULL,
    PRIMARY KEY (pid)
);

CREATE TABLE APPOINTMENT(
	pid INT NOT NULL,
    did INT NOT NULL,
    date DATE NOT NULL,
    PRIMARY KEY (pid, did, date)
);

CREATE TABLE E_PHONE_NUMBERS (
	eid INT NOT NULL,
    phone_no INT NOT NULL,
    PRIMARY KEY(eid, phone_no)
);

CREATE TABLE CARE(
	nid INT NOT NULL,
    pid INT NOT NULL,
    PRIMARY KEY(nid, pid)
);

/*
****** Referential and integrity constraints.
*/
ALTER TABLE ROOM
ADD  FOREIGN KEY (nid) REFERENCES NURSE(eid) ON DELETE SET NULL ON UPDATE CASCADE,
ADD  FOREIGN KEY (bname) REFERENCES BUILDING(name) ON DELETE CASCADE ON UPDATE CASCADE,
-- Normalization 3F for room_type.
ADD  FOREIGN KEY (room_type) REFERENCES ROOMTYPE(room_type) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DOCTOR
ADD FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (fname) REFERENCES FACULTY(name) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (supervisor_id) REFERENCES DOCTOR(eid) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE NURSE
ADD FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE FACULTY
ADD  FOREIGN KEY (manager_id) REFERENCES DOCTOR(eid) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TREATMENT
ADD FOREIGN KEY (pid) REFERENCES INPATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (did) REFERENCES DOCTOR(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TREATMENT_INCLUDE
ADD FOREIGN KEY (tid, pid, did) REFERENCES TREATMENT (tid, pid, did) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (mcode) REFERENCES MEDICINE(code) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INPATIENT
ADD FOREIGN KEY (room_id) REFERENCES ROOM(room_id) ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY (pid) REFERENCES PATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EXAMINATION
ADD FOREIGN KEY (pid) REFERENCES OUTPATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (did) REFERENCES DOCTOR(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EXAMINATION_INCLUDE
ADD FOREIGN KEY (mcode) REFERENCES MEDICINE(code) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (ex_id, pid, did) REFERENCES EXAMINATION(exam_id, pid, did) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE OUTPATIENT
ADD FOREIGN KEY (pid) REFERENCES PATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE APPOINTMENT
ADD FOREIGN KEY (pid) REFERENCES PATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (did) REFERENCES DOCTOR(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE E_PHONE_NUMBERS
ADD FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CARE
ADD FOREIGN KEY (nid) REFERENCES NURSE(eid) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (pid) REFERENCES INPATIENT(pid) ON DELETE CASCADE ON UPDATE CASCADE;

/*
****** Create indice.
*/
-- Create index for EMPLOYEE.name.
CREATE INDEX employee_name ON EMPLOYEE(name);

-- Create index for PATIENT.name.
CREATE INDEX patient_name ON PATIENT(name);

-- Create index for MEDICINE.name.
CREATE INDEX medicine_name ON MEDICINE(name);

DELIMITER $$
CREATE TRIGGER SALARY_VIOLATION
AFTER INSERT OR UPDATE OF SALARY, SUPERVISOR_SSN
 ON EMPLOYEE
FOR EACH ROW
 WHEN ( NEW.SALARY > ( SELECT SALARY FROM EMPLOYEE FULL JOIN DOCTOR WHERE EID = NEW.SUPERVISOR_ID  )) ;
DELIMITER ;

DELIMITER $$
CREATE TRIGGER SUPERVISOR_VIOLATION
AFTER INSERT OR UPDATE 
 ON EMPLOYEE
FOR EACH ROW
 WHEN ( (SELECT EID,SUPERVISOR_ID FROM EMPLOYEE FULL JOIN DOCTOR WHERE EID = NEW.SUPERVISOR_ID).SUPERVISOR_ID != NULL ) ;
DELIMITER ;

DELIMITER $$
CREATE TRIGGER MANAGERSUPERVISOR_VIOLATION
AFTER INSERT OR UPDATE 
 ON FACULTY
FOR EACH ROW
 WHEN ( ( SELECT EID,SUPERVISOR_ID,MANAGER_ID FROM DOCTOR FULL JOIN FACULTY WHERE EID = NEW.SUPERVISOR_ID ).SUPERVISOR_ID != NULL ) ;
DELIMITER ;
		

DELIMITER $$
CREATE TRIGGER FACULTY_DATETRG
BEFORE INSERT OR UPDATE 
 ON FACULTY
FOR EACH ROW
 WHEN ( NEW.START_DATE> NEW.END_DATE OR OLD.START_DATE > OLD.END_DATE);
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TREATMENT_DATETRG
BEFORE INSERT OR UPDATE 
 ON TREATMENT
FOR EACH ROW
 WHEN ( NEW.ADMITTED_DATE >= NEW.DISCHARGED_DATE OR OLD.ADMITTED_DATE >= OLD.DISCHARGED_DATE);
DELIMITER ;